### PR TITLE
Add non-location Demog Schemes

### PR DESCRIPTION
**Pull request by as2388**
All unchanged from ReDSS

### CODE REVIEW

**Review by ParthaMoman — COMMENTED** [review]
gender, recently displaced and idp camp all look good. Should age be here? 

In terms of hh_langauge, we have two thoughts:
1. We might need to allow for multiple answers here, not must have, but nice to have. How expensive is that?
2. Second given we are moving from Mogadihsu to all Somalia, it's possible we may have additional codes to add to this scheme, but we can only confirm that after looking at the data

**Comment by as2388** [comment]
> gender, recently displaced and idp camp all look good. Should age be here?

No, will remove (sorry, I was working under the assumption of "all demogs but location unchanged", have checked the doc more carefully now).

> In terms of hh_langauge, we have two thoughts:
> 
> 1. We might need to allow for multiple answers here, not must have, but nice to have. How expensive is that?

I think given project timelines I need to build the pipeline to only support single answers for now. We might be able to reconsider later.

> 2. Second given we are moving from Mogadihsu to all Somalia, it's possible we may have additional codes to add to this scheme, but we can only confirm that after looking at the data

np

**Comment by as2388** [comment]
Is it worth having a "multiple languages" code so that we can track how frequently this is occurring and then easily find the messages we need to re-code if switch to support multiple languages?

**Comment by ParthaMoman** [comment]
sorry I am confused on age? i didn't see age in the codes you shared, but it should be there

I agree with your solution on hh_langauge

**Comment by as2388** [comment]
> sorry I am confused on age? i didn't see age in the codes you shared, but it should be there

sorry you're right. The demogs I'm expecting are:
- gender
- district
- state
- region 
- zone
- age
- idp camp
- recently displaced
- hh language

This PR contains:
- gender
- **age**
- idp camp
- recently displaced
- hh language

You may need to click "show diff" on the age file because it is so long.

**Comment by lukechurch** [comment]
What does the 'hh' in 'hh language' mean?

**Review by ParthaMoman — APPROVED** [review]

**Comment by ParthaMoman** [comment]
household

**Comment by as2388** [comment]
@ParthaMoman I added a new code for multiple languages, please check

**Comment by lukechurch** [comment]
Can we call it Household Language?

I don't think the acronym is helping in this case

**Review by lukechurch — APPROVED** [review]

**Comment by as2388** [comment]
> Can we call it Household Language?

Yes.

I think the only reason for not doing so originally was so that the scheme name would fit in Coda, but we've not been doing that elsewhere.

**Comment by ParthaMoman** [comment]
no problem with this form my side

**Pull request merged**
